[FEAT] Pagina detalhes voluntario
tech-pro-bem/saude-da-rua-admin-front pull request #18
Opened 2022-11-16 00:15 UTC by MatheusBarcellosDev

## Tipo
- [X] Nova funcionalidade
- [ ] Correção de bug
- [ ] Refatoração
- [ ] Alteração de configuração de ambiente
- [ ] Outros

## Motivo
Criar uma página com os detalhes dos voluntários

## O que foi feito
- Foi criado uma pagina com os detalhes do voluntario
- Os dados estão mockados, pois ainda não temos os endpoints para trazer os dados dinamicamente

## Anexos
[Mockup FIGMA](https://www.figma.com/file/3shorGxoUcBbyAaZfXjZND/Handoff---Saúde-da-Rua---Painel-Admin?node-id=2%3A180)
[Link Card no Jira](https://uxtechprobem.atlassian.net/jira/software/c/projects/BSDR/boards/14?modal=detail&selectedIssue=BSDR-99)

![gifVolunter](https://user-images.githubusercontent.com/76540991/202051891-48743447-6915-4127-95e7-76d185e17645.gif)

2022-11-18 23:16 UTC, anajuliarauber commented
Dei uma olhada no código e me parece estar tudo certo :+1: 
Só tem um detalhe, a PR está voltada para a branch main, quando na verdade deveria estar voltada para a development

2022-11-20 13:44 UTC, lucas-lm requested changes
Parece ok, só enderecei alguns errinhos de digitação e mudei a branch que vamos fazer o merge (developer ao invés da main). Também queria entender sobre a URL da página, por que não pode ser a URL já definida?

2022-11-20 13:44 UTC, lucas-lm commented on src/App.jsx
> +import VoluteerDetails from './pages/VolunteerDetails';
```suggestion
import VolunteerDetails from './pages/VolunteerDetails';
```

2022-11-20 13:44 UTC, lucas-lm commented on src/App.jsx
> +          <Route path="/:id" element={<VoluteerDetails />} />
A rota final vai ser `/voluntarios/:id`? Qual é o problema de deixar ela desse jeito já?

Também tem esse erro de digitação (também no import) - **~Voluteer~ -> Volunteer**
```suggestion
          {/* Rota temporaria, ate que rota da tabela de voluntarios nao estiver pronta */}
          <Route path="/:id" element={<VolunteerDetails />} />
```

2022-11-20 13:44 UTC, lucas-lm commented on src/pages/VolunteerDetails.jsx
> +import MainVolunterrDetails from '../components/MainVolunterrDetails';
Erro de digitação. Esse precisa corrigir o nome do arquivo também

```suggestion
import MainVolunteerDetails from '../components/MainVolunteerDetails';
```

2022-11-20 13:44 UTC, lucas-lm commented on src/pages/VolunteerDetails.jsx
> +      <MainVolunterrDetails />
```suggestion
      <MainVolunteerDetails />
```

2022-11-20 13:44 UTC, lucas-lm commented on src/pages/VolunteerDetails.jsx
> +export default VoluteerDetails;
```suggestion
export default VolunteerDetails;
```

2022-11-20 13:44 UTC, lucas-lm commented on src/pages/VolunteerDetails.jsx
> +function VoluteerDetails() {
```suggestion
function VolunteerDetails() {
```

2022-11-20 13:44 UTC, lucas-lm commented on src/components/MainVolunterrDetails/index.jsx
> +export default MainVolunterrDetails;
```suggestion
export default MainVolunteerDetails;
```

2022-11-20 13:44 UTC, lucas-lm commented on src/components/MainVolunterrDetails/index.jsx
> +function MainVolunterrDetails() {
```suggestion
function MainVolunteerDetails() {
```

2022-11-20 13:44 UTC, lucas-lm commented on src/components/MainVolunterrDetails/index.jsx
> +  const lIMITCHAR = 255;
```suggestion
  const LIMITCHAR = 255;
```

2022-11-20 13:44 UTC, lucas-lm commented on src/components/MainVolunterrDetails/index.jsx
> +          {`${charCount}/${lIMITCHAR}`}
```suggestion
        <span
          className={`text-right ${
            charCount > LIMITCHAR ? 'text-error' : 'text-primary-black'
          }`}
        >
          {`${charCount}/${LIMITCHAR}`}
```

2022-11-20 13:44 UTC, lucas-lm commented on src/components/MainVolunterrDetails/index.jsx
> +          disabled={charCount > lIMITCHAR || !isEditing}
```suggestion
          disabled={charCount > LIMITCHAR || !isEditing}
```

2022-11-21 15:03 UTC, straubartur commented on src/App.jsx
> +          <Route path="/:id" element={<VoluteerDetails />} />
Sim @lucas-lm

2022-11-27 20:42 UTC, lucas-lm requested changes

2022-11-27 20:42 UTC, lucas-lm commented on src/pages/VolunteerDetails.jsx
> +import MainVolunterrDetails from '../components/MainVolunterrDetails';
Essa continua como antes

2022-12-11 01:25 UTC, lucas-lm approved these changes

2022-12-11 01:26 UTC, lucas-lm approved these changes

2022-12-16 17:10 UTC, closed without merging