[FEAT] Componente Modal
tech-pro-bem/saude-da-rua-admin-front pull request #9
Opened 2022-10-11 21:13 UTC by MatheusBarcellosDev

## Tipo
- [X] Nova funcionalidade
- [ ] Correção de bug
- [ ] Refatoração
- [ ] Alteração de configuração de ambiente
- [ ] Outros

## Motivo
Era necessário a confirmação da ação, no momento que o botão de excluir fosse clicado, então foi construído um modal para realizar essa confirmação    

## O que foi feito
- Foi instalado a biblioteca Radix UI para realizar a construção do modal
- Foi criado um componente chamado 'ModalDelete' com toda a instrutura do modal
- Foi importado do styleguide o icone de 'Lixeira', para dentro da pasta assets

_Obs: Ainda deve ser implementado a funcionalidade de excluir o usuário, esse componente pode receber por props o id do usuário clicado, fazendo assim a busca no BD e realizando a exclusão de fato_ 

## Anexos
[Mockup FIGMA](https://www.figma.com/file/3shorGxoUcBbyAaZfXjZND/Handoff---Saúde-da-Rua---Painel-Admin?node-id=2%3A180)
[Link Card no Jira](https://uxtechprobem.atlassian.net/jira/software/c/projects/BSDR/boards/14?modal=detail&selectedIssue=BSDR-88)
[Biblioteca Radix-Ui](https://www.radix-ui.com/docs/primitives/components/dialog)

- Modal aberto
![image](https://user-images.githubusercontent.com/76540991/195197935-ccb899b4-68af-4d32-a837-516dbd8e9c50.png)

- Modal em funcionamento
![Modal2](https://user-images.githubusercontent.com/76540991/195198538-5a8794ce-a7d4-4de7-b8dd-f3641f0f74a2.gif)

2022-10-18 00:17 UTC, anajuliarauber approved these changes
Show de bola Matheus. Deixo a minha aprovação :1st_place_medal:

2022-10-30 16:59 UTC, lucas-lm requested changes
Bom trabalho, @MatheusBarcellosDev! 

Observei que o componente está muito engessado, então estou pedindo algumas mudanças para deixar ele mais dinâmico e reaproveitável. Além disso, também vou sugerir para mudar o nome do componente de `ModalDelete` para apenas `Modal` junto com as alterações que eu pedi.

2022-10-30 16:59 UTC, lucas-lm commented on src/components/ModalDelete.jsx
> +            Confirmar ação
```suggestion
            { confirmationTitle }
```

2022-10-30 16:59 UTC, lucas-lm commented on src/components/ModalDelete.jsx
> +            Deseja mesmo realizar essa exclusão?
```suggestion
            { text }
```

2022-10-30 16:59 UTC, lucas-lm commented on src/components/ModalDelete.jsx
> +                Cancelar
```suggestion
                { cancelButtonText }
```

2022-10-30 16:59 UTC, lucas-lm commented on src/components/ModalDelete.jsx
> +              Sim, excluir
```suggestion
              { confirmationButtonText }
```

2022-10-30 16:59 UTC, lucas-lm commented on src/components/ModalDelete.jsx
> +function ModalDelete() {
O componente poderia ser parametrizado.

```suggestion
function ModalDelete({ 
    text, 
    onCommit,
    confirmationTitle="Confirmar Ação", 
    cancelButtonText="Cancelar", 
    confirmationButtonText="Confirmar" 
    }) {
```

Assim seria melhor de reutilizar ele, mesmo em casos onde a gente precise utilizá-lo para confirmação de outras coisas que não seja uma exclusão genérica. Como a maioria das props tem um valor padrão, o componente continua sendo fácil de usar e fica muito mais flexível.

Também é necessário adicionar a função de será executada em caso de confirmação por parâmetro. No caso dos modais de confirmação de exclusão, a função de callback `onCommit` será a responsável pela chamada da API para exclusão.

2022-10-30 16:59 UTC, lucas-lm commented on src/components/ModalDelete.jsx
> +            >
```suggestion
            <button
              type="button"
              className="py-3 px-16 border-[1.5px] h-12 bg-error border-error rounded-full text-base font-bold"
              onClick={ onCommit }
            >
```

2022-11-03 14:39 UTC, MatheusBarcellosDev commented on src/components/ModalDelete.jsx
> +            Confirmar ação
Valeu @MatheusBarcellosDev concordo com o seu ponto, vou fazer as alterações!

2022-11-03 14:39 UTC, MatheusBarcellosDev commented on src/components/ModalDelete.jsx
> +            Deseja mesmo realizar essa exclusão?
:+1:

2022-11-03 14:40 UTC, MatheusBarcellosDev commented on src/components/ModalDelete.jsx
> +                Cancelar
:+1:

2022-11-03 14:40 UTC, MatheusBarcellosDev commented on src/components/ModalDelete.jsx
> +              Sim, excluir
:+1:

2022-11-03 14:40 UTC, MatheusBarcellosDev commented on src/components/ModalDelete.jsx
> +function ModalDelete() {
:+1:

2022-11-03 14:40 UTC, MatheusBarcellosDev commented on src/components/ModalDelete.jsx
> +            >
:+1:

2022-11-04 01:50 UTC, lucas-lm approved these changes

2022-11-04 01:52 UTC, merged